on: 
  push:
    branches:
      - main
  workflow_dispatch:

name: ✨ Deploy to Production
env:
    DEPLOY_BRANCH: main

jobs:
  Honeybadger:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}
          environment: production
